/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package nl.randstadgroep.poc2.ccd.api;

import nl.randstadgroep.poc2.ccd.model.BranchSituation;
import org.threeten.bp.LocalDate;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-06-24T13:20:18.302050+02:00[Europe/Amsterdam]")
@Api(value = "GetBranchByNumber", description = "the GetBranchByNumber API")
public interface GetBranchByNumberApi {

    @ApiOperation(value = "", nickname = "getBranchByNumber", notes = "Returns the Branch by Number", response = BranchSituation.class, tags={ "CCDAPI", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Structure with all Branch Data and Situation result", response = BranchSituation.class) })
    @RequestMapping(value = "/GetBranchByNumber",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<BranchSituation> getBranchByNumber(@NotNull @ApiParam(value = "Branch unique number", required = true) @Valid @RequestParam(value = "BranchNumber", required = true) Long branchNumber
,@ApiParam(value = "The date for the Branch Data") @Valid @RequestParam(value = "Date", required = false) LocalDate date
);

}
