/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package nl.randstadgroep.poc2.ccd.api;

import nl.randstadgroep.poc2.ccd.model.ContactSituation;
import org.threeten.bp.LocalDate;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-06-24T13:20:18.302050+02:00[Europe/Amsterdam]")
@Api(value = "GetContactsByBranchNumber", description = "the GetContactsByBranchNumber API")
public interface GetContactsByBranchNumberApi {

    @ApiOperation(value = "", nickname = "getContactsByBranchNumber", notes = "Returns Contact(s) with a Position at Branch with specified BranchNumber with all positions at this Branch and other Branches", response = ContactSituation.class, responseContainer = "List", tags={ "CCDAPI", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = ContactSituation.class, responseContainer = "List") })
    @RequestMapping(value = "/GetContactsByBranchNumber",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<ContactSituation>> getContactsByBranchNumber(@NotNull @ApiParam(value = "Branch unique number", required = true) @Valid @RequestParam(value = "BranchNumber", required = true) Long branchNumber
,@ApiParam(value = "The date for the Contact Data") @Valid @RequestParam(value = "Date", required = false) LocalDate date
);

}
